### ISSUE TITLE
Errors when trying to compile

### ISSUE THREAD

**Issue by Teuns** [BernardoGiordano/CustomVersionSetter#1]
Getting errors when trying to compile:

<details>
find: -printf: unknown primary or operator
find: -printf: unknown primary or operator
find: -printf: unknown primary or operator
find: -printf: unknown primary or operator
linking CustomVersionSetter-master.elf
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/lib/armv6k/fpu/3dsx_crt0.o: In function `ClrLoop':
(.crt0+0x8c): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[1]: *** [/Users/teun/Downloads/CustomVersionSetter-master/CustomVersionSetter-master.elf] Error 1
make: *** [build] Error 2
</details>

Am using the latest libctru version.

**Comment by BernardoGiordano** [comment]
I think you're still using outdated versions of something or you have your path set up in a bad way. It compiles flawlessly for me.

**Comment by Teuns** [comment]
Yup, got it working by gitting the latest libctru. Thanks
